services:
  - type: web
    name: cubeai-flutter-web
    env: static
    buildCommand: flutter build web --release
    staticPublishPath: build/web
    routes:
      - type: rewrite
        source: /*
        destination: /index.html